version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "air -c .air.toml"
    ports:
      - "1323:1323"
    volumes:
      - ./:/app

  oapigen:
    image: "openapitools/openapi-generator-cli:v6.6.0"
    command: >
      /bin/bash -c \
      '
        /usr/local/bin/docker-entrypoint.sh \
          generate \
            -i /workspace/spec/openapi.yml \
            -g openapi-yaml \
            -o /workspace/spec/.dist
      '
    volumes:
      - ./:/workspace

  db:
    image: mysql:8.0
    ports:
      - "13306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: prototype
