version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "air -c .air.toml"
    ports:
      - "1323:1323"
    volumes:
      - ./:/app

  db:
    image: mysql:8.0
    ports:
      - "13306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: prototype
