openapi: 3.0.2
info:
  title: My API
  version: 1.0.0
  description: Description of my API

paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      responses:
        '200':
          description: A paged array of pets
          content:
            application/json:
              schema:
                $ref: '../schemas/pet.yml#/components/schemas/Pets'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '../schemas/error.yml#/components/schemas/Error'
  /pets/{id}:
    get:
      summary: Info for a specific pet
      operationId: findPetById
      tags:
        - pets
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: integer
            format: uint
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '../schemas/pet.yml#/components/schemas/Pet'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '../schemas/error.yml#/components/schemas/Error'
